# Generated by Django 5.0.7 on 2025-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interagent", "0002_remove_chatlog_monitored_chatmonitoring_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("endpoint", models.URLField()),
                ("capabilities", models.JSONField(default=list)),
                ("auth_token", models.CharField(blank=True, max_length=200)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
